name: jointagger
channels:
  - conda-forge          # everything except PyTorch
  - pytorch              # official PyTorch binaries
  - nvidia               # CUDA runtime (Linux)
dependencies:
  - python=3.11
  - pytorch-gpu = 2.7.*
#  - torchvision = 0.20.*       # ← explicit, GPU build
#  - torchaudio = 2.7.*
  - timm
  - msgspec
  - matplotlib

  - pip
  - pandas
  - pillow
  - tqdm
  - requests
  - scikit-image
  - pip:
      - transformers==4.51.0
      - accelerate                        #==0.29.3
      - bitsandbytes                      #==0.43.1             # 4-bit loading
      - safetensors                       #==0.4.3
      - gradio
      - huggingface_hub
      - tiktoken                      # Qwen tokenizer requirement
      - sentencepiece                    # some models need it
      - jinja2                           # chat-template rendering
      - rich                             # nicer CLI logs (optional)
      - python-dotenv>=1.0        # convenience only – optional
      - onnxruntime
      - onnxruntime-gpu
