name: jointagger
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11.9
  - pytorch-gpu=2.7              # pulls torch + torchvision + CUDA libs
  - torchvision=0.20.*
  - torchaudio=2.7.*
  - timm
  - safetensors
  - msgspec
  - pillow>=10.3
  - matplotlib
  - pandas

  - pip
  - pip:
      - gradio>=4.34.0
      - requests>=2.32
      - tqdm>=4.66
      - python-dotenv>=1.0
      - huggingface_hub
      - transformers==4.51.0
      - accelerate
      - sentencepiece
      - jinja2
  # ↓ anything else that has Conda builds ↓
  # - opencv
  # - ...
